name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: SSH and deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/cloversystore
            cd cloversy-store-web
            expect -c '
              spawn git pull origin main
              expect "Username for 'https://github.com':"
              send "${{ secrets.GH_USERNAME }}\r"
              expect "Password for 'https://${{ secrets.GH_USERNAME }}@github.com':"
              send "${{ secrets.GH_PASSWORD }}\r"
              interact
            '
            npm install
            npm run build
            pm2 restart cloversy-store-web
